[package]
name = "chem-balancer"
version = "0.1.0"
edition = "2024"

[lib]
name = "chem_balancer"
path = "rust/src/lib.rs"

[[bin]]
name = "chem_balancer"
path = "rust/src/main.rs"

[dependencies]
counter = "0.7.0"
regex = "1.11.3"
strum = "0.27.2"
strum_macros = "0.27.2"
